name: xss challenge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t xss .
      - name: Run Docker container
        run: docker run --rm -d -it -p 8080:8080 xss
      - name: Install localtunnel
        run: npm install -g localtunnel
      - name: Start localtunnel
        run: lt --port 8080 --subdomain xsschallenge
