name: firefox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'huehueh'
          password: 'anon@#@#hehe69'
      - name: Build Docker image
        run: docker pull jlesage/firefox
      - name: Run Docker container
        run: docker run -d --name=firefox -p 5800:5800 -v /docker/appdata/firefox:/config:rw jlesage/firefox
      - name: Install localtunnel
        run: npm install -g localtunnel
      - name: Start localtunnel
        run: lt --port 5800 --subdomain firefoxhuh
