name: kasm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t firefox  .
      - name: Run Docker container
        run: docker run -d -p 5800:5800 -v /docker/appdata/firefox:/config:rw jlesage/firefox

      - name: Install localtunnel
        run: npm install -g localtunnel
      - name: Start localtunnel
        run: lt --port 5800 --subdomain brave-huehue
