name: kasm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'huehueh'
          password: 'anon@#@#hehe69'
      - name: Build Docker image
        run: docker pull kasmweb/brave:1.12.0
      - name: Run Docker container
        run: sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/brave:1.12.0

      - name: Install localtunnel
        run: npm install -g localtunnel
      - name: Start localtunnel
        run: lt --port 6901 --subdomain brave-huehue
