name: ubuntu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'huehueh'
          password: 'anon@#@#hehe69'
      - name: Build Docker image
        run: docker pull accetto/ubuntu-vnc-xfce
      - name: Run Docker container
        run: docker run -d -p 25901:5901 -p 26901:6901 accetto/ubuntu-vnc-xfce
      - name: Install localtunnel
        run: npm install -g localtunnel
      - name: Start localtunnel
        run: lt --port 26901 
