name: xss
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 'huehueh'
          password: 'anon@#@#hehe69'
      - name: Build Docker image
        run: docker pull moeinfatehi/xss_vulnerability_challenges
      - name: Run Docker container
        run: sudo docker run -d -p 9003:80 moeinfatehi/xss_vulnerability_challenges
      - name: Install localtunnel
        run: npm install -g localtunnel
      - name: Start localtunnel
        run: lt --port 9003 
